version: '3.8'

services:
  # Spring Boot 백엔드
  backend:
    build: .
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=80
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tripmate?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=tripmate
      - SPRING_DATASOURCE_PASSWORD=tripmate123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    depends_on:
      - db
      - redis
    networks:
      - tripmate-network
    restart: unless-stopped

  # React 프론트엔드 (프로덕션 빌드)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - tripmate-network
    restart: unless-stopped

  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tripmate
      MYSQL_USER: tripmate
      MYSQL_PASSWORD: tripmate123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tripmate-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - tripmate-network
    restart: unless-stopped

networks:
  tripmate-network:
    driver: bridge

volumes:
  mysql_data:
